# Generated by Django 4.1.3 on 2022-11-27 21:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subscribe',
            field=models.ManyToManyField(related_name='category', to=settings.AUTH_USER_MODEL),
        ),
    ]
